name: Tests
on:
  push:
    branches-ignore:
      - "master"
      - "main"
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-back:
    name: ğŸ“¦ Build Back
    runs-on: ubuntu-latest
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v3
      - run: echo ${{ github.ref_name }} develop
      - name: ğŸ§¶ Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./back/yarn.lock"
      - name: ğŸï¸ Cache Dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: back/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('back/yarn.lock') }}
      - name: ğŸ“¦ Install Dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: yarn --cwd ./back install
  unit-test:
    name: "ğŸ§ª Unit Tests"
    if: contains(github.event.head_commit.message, '(no unit-test)') != true
    runs-on: ubuntu-latest
    needs:
      - build-back
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v3
      - run: echo ${{ github.ref_name }} develop
      - name: ğŸ§¶ Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./back/yarn.lock"
      - name: ğŸ“¦ Cache Dependencies
        uses: actions/cache@v3
        with:
          path: back/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('back/yarn.lock') }}
      - name: ğŸ§ª Run Unit Tests
        working-directory: ./back
        run: yarn test:unit:ci
  build-front-admin:
    name: ğŸ“¦ Front Admin Build
    runs-on: ubuntu-latest
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v3
      - name: ğŸ§¶ Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./front-admin/yarn.lock"
      - name: ğŸï¸ Cache Dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: front-admin/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('front-admin/yarn.lock') }}
      - name: ğŸ“¦ Install Dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: yarn --cwd ./front-admin install
  end-to-end-test:
    name: ğŸ–¼ï¸ End-to-End Tests
    if: |
      contains(github.event.head_commit.message, '(_deploy)') ||
      ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    needs: build-front-admin
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v3

      - name: ğŸ§¶ Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./front-admin/yarn.lock"

      - name: ğŸ“¦ Install Dependencies
        run: yarn --cwd ./front-admin install # Installez les dÃ©pendances du projet dans le dossier "front-admin"

      - name: ğŸ‘€ Build for tests (dev keys)
        run: yarn --cwd ./front-admin build # Construisez le projet pour les tests E2E (si nÃ©cessaire)

      - name: ğŸ“¦ Install Cypress
        run: yarn --cwd ./front-admin add cypress # Installez Cypress localement dans le dossier "front-admin"

      - name: ğŸ–¼ Cypress Tests
        run: cd front-admin && yarn test:e2e
        timeout-minutes: 10
        # with:
        #   config-file: cypress.config.js
        #   # start: "yarn  dev"
        #   browser: chrome
        #   headed: false
        #   record: false
  deploy:
    name: ğŸš€ deploy front admin
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - end-to-end-test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build the project
        run: yarn --cwd ./front-admin build

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: ".front-admin/dist"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
