name: Tests
on:
  push:
    branches-ignore:
      - "master"
      - "main"
jobs:
  build-back:
    name: ğŸ“¦ Build Back
    runs-on: ubuntu-latest
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v3
      - run: echo ${{ github.ref_name }} develop
      - name: ğŸ§¶ Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./back/yarn.lock"
      - name: ğŸï¸ Cache Dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: back/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('back/yarn.lock') }}
      - name: ğŸ“¦ Install Dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: yarn --cwd ./back install
  unit-test:
    name: "ğŸ§ª Unit Tests"
    if: contains(github.event.head_commit.message, '(no unit-test)') != true
    runs-on: ubuntu-latest
    needs:
      - build-back
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v3
      - run: echo ${{ github.ref_name }} develop
      - name: ğŸ§¶ Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./back/yarn.lock"
      - name: ğŸ“¦ Cache Dependencies
        uses: actions/cache@v3
        with:
          path: back/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('back/yarn.lock') }}
      - name: ğŸ§ª Run Unit Tests
        working-directory: ./back
        run: yarn test:unit:ci
  build-front-admin:
    name: ğŸ“¦ Front Admin Build
    runs-on: ubuntu-latest
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v3
      - name: ğŸ§¶ Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "./front-admin/yarn.lock"
      - name: ğŸï¸ Cache Dependencies
        uses: actions/cache@v3
        id: cache-primes
        with:
          path: front-admin/node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('front-admin/yarn.lock') }}
      - name: ğŸ“¦ Install Dependencies
        if: steps.cache-primes.outputs.cache-hit != 'true'
        run: yarn --cwd ./front-admin install
  end-to-end-test:
    name: ğŸ–¼ï¸ End-to-End Tests
    if: |
      contains(github.event.head_commit.message, '(_deploy)') ||
      ${{ github.ref_name == 'develop' }}
    runs-on: ubuntu-latest
    needs: build-front-admin
    steps:
      - name: âœ¨ Checkout
        uses: actions/checkout@v3
      - name: ğŸ§¶ Install Yarn
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: ğŸ“¦ Retrieve Dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-npm-v3-${{ hashFiles('yarn.lock') }}
      - name: ğŸ‘€ Build for tests (dev keys)
        if: contains(github.event.head_commit.message, '(fall_deploy)') != true
        run: yarn build
      - name: ğŸ“¦ Install Cypress binaries
        run: npx cypress install
      - name: ğŸ–¼ Cypress Tests
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          config-file: cypress.config.ts
          start: "yarn serve"
          browser: chrome
          headless: true
          record: false
          env: true
        env:
          CYPRESS_MODE: ${{contains(github.event.head_commit.message, '(fall_deploy)') && 'prod' || 'dev'}}
